import { buildSummary } from "@/lib/artifacts";
import {
  getProfileJourneyRecords,
  getTemporaryJourneyRecords,
  type ProfileJourneyRecord,
  type TemporaryJourneyRecord
} from "@/lib/journey-store";
import type { RedefinedMode, RedefinedResult } from "@/lib/redefined";
import type { WorkspaceArtifact } from "@/lib/workspace-types";

const ARCHIVED_KEY = "docredefined.archivedArtifacts";

export type ArtifactType = WorkspaceArtifact["artifactType"];

export type ArtifactLibraryItem = {
  id: string;
  recordId: string;
  title: string;
  type: ArtifactType;
  displayType?: string;
  sourceWorkspaceId: string;
  sourceWorkspaceName: string;
  projectId?: string;
  mode: RedefinedMode;
  format: string;
  content: string;
  createdAt: string;
  updatedAt: string;
  persistence: "temporary" | "local_profile";
  href: string;
  origin: "artifact" | "follow_up";
};

export { ARTIFACT_TYPE_LABELS } from "@/lib/artifact-generation";

/** Extracts the exportable text + format from a result. */
function deriveExport(result: RedefinedResult): { content: string; format: string } {
  if (result.artifactPreview?.body) {
    return { content: result.artifactPreview.body, format: result.artifactPreview.format };
  }
  return { content: buildSummary(result), format: "markdown" };
}

/** Infers an artifact type when a follow-up produced an output without explicit metadata. */
function deriveArtifactType(result: RedefinedResult): ArtifactType {
  const format = result.artifactPreview?.format;
  if (format === "checklist") return "checklist";
  if (format === "ticket") return "ticket";
  if (format === "code") return "code";

  const text = `${result.workspaceType ?? ""} ${result.title}`.toLowerCase();
  if (text.includes("runbook")) return "runbook";
  if (text.includes("business plan")) return "business_plan";
  if (text.includes("summary")) return "summary";
  if (text.includes("checklist")) return "checklist";
  if (text.includes("ticket")) return "ticket";
  return "document";
}

function recordToItems(
  record: ProfileJourneyRecord | TemporaryJourneyRecord,
  persistence: "temporary" | "local_profile"
): ArtifactLibraryItem[] {
  const meta = record.workspaceMeta ?? record.result.workspaceMeta;
  const sourceWorkspaceId = meta?.workspaceId ?? record.id;
  const sourceWorkspaceName = meta?.workspaceName ?? record.title;
  const projectId = meta?.projectId;
  const href = `/workspaces/${encodeURIComponent(sourceWorkspaceId)}`;

  const base = {
    recordId: record.id,
    sourceWorkspaceId,
    sourceWorkspaceName,
    projectId,
    persistence,
    href
  };

  const items: ArtifactLibraryItem[] = [];

  // Canonical artifacts (created for artifact-mode workspaces).
  const artifacts = record.result.workspaceArtifacts ?? record.artifacts ?? [];
  const mainExport = deriveExport(record.result);
  for (const artifact of artifacts) {
    // User-generated artifacts carry their own content; legacy ones fall back
    // to the workspace's exportable preview.
    const exported = artifact.content
      ? { content: artifact.content, format: artifact.format ?? "markdown" }
      : mainExport;
    items.push({
      ...base,
      id: artifact.id,
      title: artifact.name,
      type: artifact.artifactType,
      displayType: artifact.displayType,
      mode: artifact.sourceMode,
      format: exported.format,
      content: exported.content,
      createdAt: artifact.createdAt,
      updatedAt: artifact.updatedAt,
      origin: "artifact"
    });
  }

  // Outputs generated by follow-up prompt runs (artifact path or with a preview).
  const followUps = record.result.workspaceFollowUpResults ?? [];
  for (const followUp of followUps) {
    const hasArtifactOutput =
      followUp.mode === "artifact" || Boolean(followUp.content.artifactPreview);
    if (!hasArtifactOutput) continue;

    const exported = deriveExport(followUp.content);
    items.push({
      ...base,
      id: followUp.id,
      title: followUp.title,
      type: deriveArtifactType(followUp.content),
      mode: followUp.mode,
      format: exported.format,
      content: exported.content,
      createdAt: followUp.createdAt,
      updatedAt: followUp.createdAt,
      origin: "follow_up"
    });
  }

  return items;
}

/** All generated artifacts across the owner's workspaces, newest first. */
export function getArtifactLibraryItems(profileId?: string): ArtifactLibraryItem[] {
  const items = profileId
    ? getProfileJourneyRecords(profileId).flatMap((record) => recordToItems(record, "local_profile"))
    : getTemporaryJourneyRecords().flatMap((record) => recordToItems(record, "temporary"));

  return items.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/** Looks up a single artifact by its id. */
export function getArtifactLibraryItem(
  artifactId: string,
  profileId?: string
): ArtifactLibraryItem | null {
  const decoded = decodeURIComponent(artifactId);
  return (
    getArtifactLibraryItems(profileId).find(
      (item) => item.id === decoded || item.id === artifactId
    ) ?? null
  );
}

/** Artifacts related to the given one (same workspace, then same type). */
export function getRelatedArtifacts(
  item: ArtifactLibraryItem,
  profileId?: string,
  limit = 4
): ArtifactLibraryItem[] {
  const all = getArtifactLibraryItems(profileId).filter((entry) => entry.id !== item.id);
  const sameWorkspace = all.filter((entry) => entry.sourceWorkspaceId === item.sourceWorkspaceId);
  const sameType = all.filter(
    (entry) => entry.sourceWorkspaceId !== item.sourceWorkspaceId && entry.type === item.type
  );
  return [...sameWorkspace, ...sameType].slice(0, limit);
}

export function getArchivedArtifactIds(): string[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(ARCHIVED_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed.filter((id): id is string => typeof id === "string") : [];
  } catch {
    return [];
  }
}

export function toggleArchivedArtifact(artifactId: string): string[] {
  const current = getArchivedArtifactIds();
  const next = current.includes(artifactId)
    ? current.filter((id) => id !== artifactId)
    : [...current, artifactId];

  try {
    window.localStorage.setItem(ARCHIVED_KEY, JSON.stringify(next));
  } catch {
    // Archive state is best effort only.
  }

  return next;
}

/** Suggests a download filename + extension for an artifact. */
export function artifactDownloadName(item: ArtifactLibraryItem): string {
  const slug =
    item.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 60) || "artifact";
  const ext = item.format === "code" || item.format === "email" ? "txt" : "md";
  const date = new Date().toISOString().slice(0, 10);
  return `${slug}-${item.type}-${date}.${ext}`;
}
